# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4c0e66fb6b79a365ced22af82ef30ff19e59b262b376c1f7e2d4e0762b4f07ae3fbb9cc9e2a7b911bd7868a246e04732d94f327d1af730ed7cb6b7acb9019f05

test:
  secret_key_base: 619f34d1c0ce02a70eae2ae0687a8a873e25a33a124da4b914bb0696d4bd24c2f578236667d4688113885570271bf2709c66e9b62204699fc00536041991bb44

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
