# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dc6cfc4e384fcf323d66acabb0c4598a0c559181685024acb012b5656af3b0e9a495f30f188fb23b3d2c0775c2ad887c2f4613706040cedf775e10a631ec9842

test:
  secret_key_base: e4ecf9dd772f3644adaa5ec7a31f615683761f5e7db16f508b5e3318ed10a2b580dd6776fb772490346b392c073bfc0c94edb48ff8f9222cdc0470d0203e192d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
